name: 'Conventional PR'
description: 'Validate a PR title and commits against a Conventional Commits preset.'
inputs:
  config-preset:
    description: 'Name of conventional changelog config preset.'
    required: false
    default: 'beemo'
  require-multiple-commits:
    description: 'Squash merges require multiple commits for the PR title to be preserved.'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'lib/index.js'
branding:
  icon: 'git-commit'
  color: 'orange'
